#!/bin/env bash

export XDG_CURRENT_DESKTOP='dwl'
export MOZ_ENABLE_WAYLAND=1
export GDK_BACKEND=wayland
export QT_QPA_PLATFORM="wayland-egl"
export QT_WAYLAND_FORCE_DPI=96
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
export QUTE_SKIP_WAYLAND_CHECK=1
export SDL_VIDEODRIVER="wayland"
export WLR_NO_HARDWARE_CURSORS=1

# launches a session dbus instance
dbuslaunch="$(which dbus-launch 2>/dev/null)"
if [ -n "$dbuslaunch" ] && [ -x "$dbuslaunch" ] && [ -z "$DBUS_SESSION_BUS_ADDRESS" ]; then
  eval $($dbuslaunch --sh-syntax --exit-with-session)
fi

dbus-update-activation-environment --all >/dev/null 2>&1

# MPDRIS_PID=$(pgrep -f mpDris2)
PIPEWIRE_PID=$(pgrep -f pipewire)

# pipewire
[ -z "$PIPEWIRE_PID" ] && pipewire &

# mpDris2
# kill -9 "$MPDRIS_PID"
# mpDris2 &

killall mpd
mpd &

# dunst
killall dunst
dunst &

# simulate a do-while
do=true
while $do || [ -f /tmp/restart_dwl ]; do
  do=false
  rm -rf /tmp/restart_dwl >/dev/null 2>&1
  dwl -s dwlb >~/.config/dwl/run/log.txt
  # dwl -s somebar >~/.config/dwl/run/log.txt 2>&1
  # dwl -s dwlb >~/.config/dwl/run/log.txt 2>&1
  [ -f /tmp/restart_dwl ] && echo Restarting dwl...
done
