#!/bin/sh

background='#1a1a1a'
mainBlue='#268bd2'
fontsize=16
font="sans $fontsize"
horispacing=14

export BEMENU_OPTS="-i \
  -p ''\
  --tb $background \
  --fn '$font'\
  --tf $mainBlue \
  --fb $background \
  --nb $background \
  --hb $background \
  --hf $mainBlue \
  --hp $horispacing \
  --binding vim"
